### ISSUE TITLE
Kadira: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by gbachik** [meteorhacks/kadira#136] opened 2015-02-12 01:48 UTC
I'm running the latest version of meteor 1.0.3.1, and kadira 2.18.0 on modulus.io

I'm getting this in my logs:

```
Kadira: getaddrinfo ENOTFOUND
Kadira: getaddrinfo ENOTFOUND
Kadira: getaddrinfo ENOTFOUND
Kadira: getaddrinfo ENOTFOUND
Kadira: getaddrinfo ENOTFOUND
Kadira: getaddrinfo ENOTFOUND
Kadira: getaddrinfo ENOTFOUND
Kadira: getaddrinfo ENOTFOUND
Kadira: getaddrinfo ENOTFOUND
Kadira: getaddrinfo ENOTFOUND
Kadira: getaddrinfo ENOTFOUND
Kadira: getaddrinfo ENOTFOUND
Kadira: getaddrinfo ENOTFOUND
Kadira: getaddrinfo ENOTFOUND
```

but everything seems to be running fine?
Any idea whats up or tips on how to fix this?

**Comment by arunoda** [comment] 2015-02-12 01:50
Pretty weird. Do you see data on your kadira dashboard.
This is because of an DNS issue.

Could you modulus guys on this a bit. Kadira uses a domain name called
engine.kadira.io
Ask them to check on that domain.

**Comment by gbachik** [comment] 2015-02-12 02:04
@arunoda Yeh I seem to be getting my data just fine so I'm not sure what this is about?
I'll ask the guys at modulus too!

**Comment by arunoda** [comment] 2015-02-12 02:05
We are using cloudflare for DNS.
May be this something random issue on Cloudflare or Modulus DNS setup.

I'll ask from Cloudflare too.

**Comment by gbachik** [comment] 2015-02-14 04:11
@arunoda Still waiting to hear back from the modulus guys, but just thought I'd update you.

after upgrading modulus' deploy script via npm this issue now stops my site from loading at all.
I was forced to comment out kadira for now. 

Thanks for the quick responses I'll let you know what the modulus folks say

**Comment by arunoda** [comment] 2015-02-14 04:31
Okay. That's bad. There will be something going on here.

I will give it a try today. Then let me see if there is something we can do
from our end.

If we couldn't found the issue. I am happy to try your app and reproduce
the issue.

I will get back to you soon. (Within today)

**Comment by arunoda** [comment] 2015-02-14 04:43
Anyway, I would like to see your .meteor/versions file. Send me an email if
you don't want to share it here.

**Comment by gbachik** [comment] 2015-02-14 04:51
I don't mind posting it if it could help someone else in the future:
```
accounts-base@1.1.3
accounts-password@1.0.6
accounts-ui@1.1.4
accounts-ui-unstyled@1.1.6
application-configuration@1.0.4
autoupdate@1.1.5
base64@1.0.2
binary-heap@1.0.2
blaze@2.0.4
blaze-tools@1.0.2
boilerplate-generator@1.0.2
callback-hook@1.0.2
check@1.0.4
ddp@1.0.14
deps@1.0.6
dsyko:jquery-ui-touch-punch@1.2.4
ejson@1.0.5
email@1.0.5
fastclick@1.0.2
follower-livedata@1.0.3
geojson-utils@1.0.2
html-tools@1.0.3
htmljs@1.0.3
http@1.0.10
id-map@1.0.2
iron:controller@1.0.7
iron:core@1.0.7
iron:dynamic-template@1.0.7
iron:layout@1.0.7
iron:location@1.0.7
iron:middleware-stack@1.0.7
iron:router@1.0.7
iron:url@1.0.7
jquery@1.11.3
json@1.0.2
launch-screen@1.0.1
less@1.0.12
livedata@1.0.12
localstorage@1.0.2
logging@1.0.6
meteor@1.1.4
meteor-platform@1.2.1
meteorhacks:async@1.0.0
meteorhacks:kadira@2.18.2
meteorhacks:meteorx@1.2.1
meteorhacks:npm@1.2.2
meteorhacks:stripe@1.0.0
minifiers@1.1.3
minimongo@1.0.6
mizzao:timesync@0.3.0
mobile-status-bar@1.0.2
mongo@1.0.11
mongo-livedata@1.0.7
mquandalle:jade@0.4.1
mquandalle:stylus@1.0.10
mrt:jquery-ui@1.9.2
mrt:moment@2.8.1
npm-bcrypt@0.7.7
observe-sequence@1.0.4
ordered-dict@1.0.2
percolatestudio:synced-cron@1.1.0
random@1.0.2
reactive-dict@1.0.5
reactive-var@1.0.4
reload@1.1.2
retry@1.0.2
routepolicy@1.0.4
sacha:spin@2.0.4
service-configuration@1.0.3
session@1.0.5
sha@1.0.2
spacebars@1.0.5
spacebars-compiler@1.0.4
srp@1.0.2
templating@1.0.11
tracker@1.0.5
ui@1.0.5
underscore@1.0.2
url@1.0.3
webapp@1.1.6
webapp-hashing@1.0.2
```
I was loving kadira before this so its really a bummer!
My app is live @ skive.io right now and I can give you the access to the repo if need be.

**Comment by arunoda** [comment] 2015-02-14 04:53
Thanks. I will give it a try first. Let's see.

**Comment by arunoda** [comment] 2015-02-14 06:54
I've reproduced the issue. It seems like it's an issue of our meteorx package.
I tested locally with the bundle generated by modulus deploy. It worked locally.

Something has happened on their runtime. I have an idea to fix it. I'll work on it.
But, there is something wrong with their deployment env or build system.

**Comment by arunoda** [comment] 2015-02-14 07:41
I've released a new version. Try that.

**Comment by gbachik** [comment] 2015-02-17 21:49
I've been running the new version for about an hour now with no issues!
Thanks for being so on top of this!

You got yourself a new paying customer!
ps the modulus people finally got back to me and said that is was possible my mongo connection was going out intermittently?

I was under the impression meteor attempts to keep the connection live?

Anyways It's working fine as of now!

**Comment by arunoda** [comment] 2015-02-17 22:04
Thanks.

Modulus converts a meteor app into a NodeJs app. It's not perfect all the
times. That could be an issue.

Anyway, I wanted to fix this if we do it in our side.its great, now
everything seems to fine.

**Comment by gbachik** [comment] 2015-02-17 23:13
```
Kadira: getaddrinfo ENOTFOUND
```

After a few hours I got this in my log again.
It didn't break the site or anything as of now,
but just a warning.

**Comment by arunoda** [comment] 2015-02-17 23:15
Actually, I am not sure about that.
But I fixed the slow startup issue.
This is something I don't have the control.

**Comment by jamescoletti** [comment] 2015-02-24 18:16
We are also seeing the same intermittent behavior. Meteor 1.x & Kadira 2.19.6 on Modulus occasionally loses connection and reports `Kadira: getaddrinfo ENOTFOUND`. I'm not sure if it ever recovers on its own, but app restart fixes it. We will be migrating to AWS soon so we'll be able to confirm if it's strictly Modulus-related.

**Comment by arunoda** [comment] 2015-02-24 19:23
Thanks for that. Let me know how it was.

**Comment by jakobloekke** [comment] 2015-03-03 08:55
I'm experiencing the same issue now. Also on Modulus. I'll be interested to know if moving to AWS fixes it.

**Comment by arunoda** [comment] 2015-03-03 08:56
@jakobloekke we did some related fix for that as well.
Hope you are using the latest version of Kadira.

**Comment by flean** [comment] 2015-03-06 21:56
I have this issue also, have latest Meteor. 1.0.3.2 and Kadira 2.19.6 on modulus.io

**Comment by wulfmeister** [comment] 2015-03-09 13:21
Fwiw, I'm seeing this error on Modulus also. Meteor 1.0.3.2 and Kadira 2.19.6.

**Comment by sheldonkotyk** [comment] 2015-03-10 06:07
Same issue for me on Modulus. The ERRNOTFOUND showed up once and got this error at the end. Then it gave me the ERRNOTFOUND again about a minute later.

 [2015-03-10T05:57:12.496Z] Application started with pid 5961
Kadira: completed instrumenting the app
Kadira: successfully authenticated
Kadira: getaddrinfo ENOTFOUND
Kadira: Remote CPU profiling started for 30 secs.
Kadira: Uploding the taken CPU profile.
Exception while invoking method 'kadira.profileCpu' Error: failed [403] <?xml version="1.0" encoding="UTF-8"?> <Error><Code>AccessDenied</Code><Message>Request has expired</Message><Expires>2015-03-10T05:59:59Z</Expires><ServerTime>2015-03-10T06:03:32Z</ServerTime><RequestId>7F673F6FFE05FE63</RequestId><HostId>9T6NmYyxDmwOZeJ6BSPZe7nJ+QNagViP9AXrrCb09pjGCchrtsBDvl4fGvwhOQMp</HostId></Error>
    at Object.Future.wait (/mnt/data/1/node_modules/fibers/future.js:326:15)
    at Object.<anonymous> (packages/meteor/helpers.js:119:1)
    at Object.HTTP.call (packages/meteorhacks:kadira/lib/hijack/http.js:10:1)
    at Object.HTTP.put (packages/http/httpcall_common.js:67:1)
    at uploadProfile (packages/meteorhacks:kadira-profiler/lib/server.js:83:1)
    at remoteProfileCPU (packages/meteorhacks:kadira-profiler/lib/server.js:36:1)
    at [object Object].Meteor.methods.kadira.profileCpu (packages/meteorhacks:kadira-profiler/lib/server.js:8:1)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:160:1)
    at packages/check/match.js:109:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    - - - - -
    at makeErrorByStatus (packages/http/httpcall_common.js:12:1)
    at Request._callback (packages/http/httpcall_server.js:98:1)
    at Request.self.callback (/mnt/data/1/node_modules/request/request.js:344:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/mnt/data/1/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/mnt/data/1/node_modules/request/request.js:1187:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
[2015-03-10T05:57:12.496Z] Application started with pid 5961
Kadira: completed instrumenting the app
Kadira: successfully authenticated
Kadira: getaddrinfo ENOTFOUND
Kadira: Remote CPU profiling started for 30 secs.
Kadira: Uploding the taken CPU profile.
Exception while invoking method 'kadira.profileCpu' Error: failed [403] <?xml version="1.0" encoding="UTF-8"?> <Error><Code>AccessDenied</Code><Message>Request has expired</Message><Expires>2015-03-10T05:59:59Z</Expires><ServerTime>2015-03-10T06:03:32Z</ServerTime><RequestId>7F673F6FFE05FE63</RequestId><HostId>9T6NmYyxDmwOZeJ6BSPZe7nJ+QNagViP9AXrrCb09pjGCchrtsBDvl4fGvwhOQMp</HostId></Error>
    at Object.Future.wait (/mnt/data/1/node_modules/fibers/future.js:326:15)
    at Object.<anonymous> (packages/meteor/helpers.js:119:1)
    at Object.HTTP.call (packages/meteorhacks:kadira/lib/hijack/http.js:10:1)
    at Object.HTTP.put (packages/http/httpcall_common.js:67:1)
    at uploadProfile (packages/meteorhacks:kadira-profiler/lib/server.js:83:1)
    at remoteProfileCPU (packages/meteorhacks:kadira-profiler/lib/server.js:36:1)
    at [object Object].Meteor.methods.kadira.profileCpu (packages/meteorhacks:kadira-profiler/lib/server.js:8:1)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:160:1)
    at packages/check/match.js:109:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    - - - - -
    at makeErrorByStatus (packages/http/httpcall_common.js:12:1)
    at Request._callback (packages/http/httpcall_server.js:98:1)
    at Request.self.callback (/mnt/data/1/node_modules/request/request.js:344:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/mnt/data/1/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/mnt/data/1/node_modules/request/request.js:1187:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
Kadira: getaddrinfo ENOTFOUND

**Comment by arunoda** [comment] 2015-03-10 06:09
The other error is a CPU profile issue and it's common if you delay taking
the CPU profile.
You need to do it within 10 minutes.

**Comment by sheldonkotyk** [comment] 2015-03-10 06:10
OK, It was no more than 2 minutes. Weird.

**Comment by sheldonkotyk** [comment] 2015-03-10 06:11
Never mind. I meant 2 minutes from the console. My guess is you meant 10 minutes from the dashboard click.

**Comment by sheldonkotyk** [comment] 2015-03-10 06:14
Yup. it worked.

**Comment by arunoda** [comment] 2015-03-10 06:14
Yes it is.

**Comment by jakobloekke** [comment] 2015-03-10 08:51
I'm getting a lot ```Kadira: getaddrinfo ENOTFOUND``` errors still.

Here's my versions-file:

```
accounts-base@1.1.3
accounts-password@1.0.6
aldeed:autoform@4.2.2
aldeed:collection2@2.3.2
aldeed:simple-schema@1.3.0
anti:i18n@0.4.3
application-configuration@1.0.4
autoupdate@1.1.5
base64@1.0.2
binary-heap@1.0.2
blaze@2.0.4
blaze-tools@1.0.2
boilerplate-generator@1.0.2
callback-hook@1.0.2
cfs:http-methods@0.0.27
check@1.0.4
chuangbo:cookie@1.1.0
coffeescript@1.0.5
dburles:collection-helpers@1.0.2
dburles:mongo-collection-instances@0.2.6
ddp@1.0.14
deps@1.0.6
ejson@1.0.5
email@1.0.5
fastclick@1.0.2
follower-livedata@1.0.3
fourseven:scss@2.0.0_1
geojson-utils@1.0.2
houston:admin@2.0.3
html-tools@1.0.3
htmljs@1.0.3
http@1.0.10
id-map@1.0.2
iron:controller@1.0.7
iron:core@1.0.7
iron:dynamic-template@1.0.7
iron:layout@1.0.7
iron:location@1.0.7
iron:middleware-stack@1.0.7
iron:router@1.0.7
iron:url@1.0.7
jakobloekke:jquery-scrolldepth@1.0.0
jquery@1.11.3
json@1.0.2
launch-screen@1.0.1
less@1.0.12
livedata@1.0.12
localstorage@1.0.2
logging@1.0.6
manuelschoebel:wait-on-lib@0.3.0
markdown@1.0.3
matb33:collection-hooks@0.7.6
meteor@1.1.4
meteor-platform@1.2.1
meteorhacks:async@1.0.0
meteorhacks:fast-render@2.3.1
meteorhacks:inject-data@1.2.2
meteorhacks:kadira@2.19.6
meteorhacks:meteorx@1.3.1
meteorhacks:npm@1.2.2
meteorhacks:picker@1.0.1
meteorhacks:subs-manager@1.3.0
minifiers@1.1.3
minimongo@1.0.6
mobile-status-bar@1.0.2
momentjs:moment@2.8.4
mongo@1.0.11
mongo-livedata@1.0.7
mrt:canvas-resize@0.0.1
mrt:moment@2.8.1
npm-bcrypt@0.7.7
npm-container@1.0.0
observe-sequence@1.0.4
ordered-dict@1.0.2
particle4dev:cheerio@1.1.0
percolate:synced-cron@1.1.1
percolatestudio:percolatestudio-mixpanel@0.5.0
raix:handlebar-helpers@0.2.4
random@1.0.2
reactive-dict@1.0.5
reactive-var@1.0.4
reload@1.1.2
retry@1.0.2
reywood:publish-composite@1.3.5
routepolicy@1.0.4
rzymek:moment-locale-da@2.8.4
sacha:spin@2.0.4
schnie:uploader@2.0.3
service-configuration@1.0.3
session@1.0.5
sha@1.0.2
spacebars@1.0.5
spacebars-compiler@1.0.4
srp@1.0.2
templating@1.0.11
tmeasday:paginated-subscription@0.2.4
tmeasday:publish-counts@0.3.4
todda00:friendly-slugs@0.2.0
tracker@1.0.5
ui@1.0.5
underscore@1.0.2
url@1.0.3
warrenmcquinn:meteor-scrollreveal@1.0.1
webapp@1.1.6
webapp-hashing@1.0.2
wylio:mandrill@0.2.1
```

**Comment by arunoda** [comment] 2015-03-10 08:54
Hmm. That's weird.

**Comment by jamescoletti** [comment] 2015-03-18 03:06
Sorry for the delay on this, but we've migrated to AWS since 3/14 and no Kadira interruptions or log entries containing `Kadira: getaddrinfo ENOTFOUND`. I would thus conclude the issue appears to be specific to the Modulus hosting environment.

**Comment by arunoda** [comment] 2015-03-18 03:08
Thanks for mentioning that. May be I will talk directly to their support.

**Comment by timtrendlier** [comment] 2015-04-22 19:22
Any update on this from Modulus support? 

I just got setup with Modulus for meteor and using compose.io for Mongo with oplog, both in the same Amazon zone.... site seems fine, but when I test with meteor-down to attempt scaling, it dies because of this error.

I accidentally left meteorhacks:cluster in there, which shouldn't be needed for Modulus, so I'll try that before commenting out kadira.

**Comment by timtrendlier** [comment] 2015-04-23 02:02
Issue still exists after removing cluster.

/usr/local/lib/node_modules/meteor-down/lib/mdown.js:47
    if(error) throw error;
                    ^
Network error: ws://subdomain.mod.bz:80/websocket: getaddrinfo ENOTFOUND

**Comment by arunoda** [comment] 2015-04-23 02:48
This is not a Kadira issue. It's a network issue.

**Comment by arunoda** [comment] 2015-04-23 02:49
I am going to close this. 
Best idea is to contact modulus support.

**Closed by arunoda** 2015-04-23 02:49 UTC

**Comment by jperl** [comment] 2015-05-18 20:04
Seeing this in modulus as well

**Comment by acemtp** [comment] 2015-09-01 07:58
I had it 3 times this night (digital ocean)

**Comment by Joostvanderlaan** [comment] 2015-11-27 15:16
@arunoda  seeing this in Tutum + AWS EC2 instances as well every once in a while

**Comment by nilsi** [comment] 2016-01-29 16:13
Yes its a network issue! Would be great if you could specify that in the error message.

**Comment by oskareke** [comment] 2016-06-16 07:33
+1, having the same problem here.. Following a bunch of those  'getaddrinfo ENOTFOUND' my app is now alternating between 'Unable to connect to any application instances' and seeing the markup but no data on the client. 

I have my app running on a small instance (396mb), could it be a performance issue?

**Comment by oskareke** [comment] 2016-06-16 09:13
I'm having the same issue on Modulus, and after getting the ‘Kadira: getaddrinfo ENOTFOUND’ a few times the client gives me either ‘Unable to connect to any application instances.’ or the markup shows up but no data. 

My app is running on a small servo (396 mb), could server performance be the issue in my case?

**Comment by sunlee-newyork** [comment] 2016-10-28 11:55
+1, seeing these logs on Galaxy-hosted app.
Multiple lines of `Kadira Error: Reached maximum retry limit for getaddrinfo ENOTFOUND enginex.kadira.io enginex.kadira.io:443` and two lines of `Kadira Error: Agent Error: 404`

**Comment by StyxUA** [comment] 2016-10-28 16:30
Same here (Aptible-hosted app), a lot of `Kadira Error: Reached maximum retry limit for getaddrinfo ENOTFOUND enginex.kadira.io enginex.kadira.io:443`

**Comment by Jarskih** [comment] 2017-02-17 14:05
I am having problems as well.
It seems enginex.kadira.io is blocked in China. Anything we could do?

> Pinging elb083924-1224143031.us-east-1.elb.amazonaws.com [54.163.241.129] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

> Ping statistics for 54.163.241.129:
>     Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
